  GNU nano 7.2                      .travis.yml                       Modified

language: node_js
node_js:
  - "stable"
 dist: focal
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

